<?php

/**

* Ultimate_Slider extension

*

* NOTICE OF LICENSE

*

* This source file is subject to the MIT License

* that is bundled with this package in the file LICENSE.txt.

* It is also available through the world-wide-web at this URL:

* http://opensource.org/licenses/mit-license.php

*/

/**

*

* @category       Images & Media

* @package        Ultimate_Slider

* @copyright      Copyright (c) 2015

* @license        http://opensource.org/licenses/mit-license.php MIT License

*/

/**

* Slider list template

*

* @category    Images & Media

* @package     Ultimate_Slider

* @author      Rajasingh and Manikandan D

* @modified    2015-11-21 04:54:53 PM IST

*/

$countOfSlider = count($this->retrieveData());

?>
<?php if($countOfSlider == 1){ ?>
<div class="block-content banner_left">
   <?php $sliderdata = $this->retrieveData();
         $sliderdata = $sliderdata[0]; 
    ?>	
   <div class="slideshow-container">

				<a href="#"><video id="vidplayer" width="100%" height="auto" autoplay="autoplay" type="video/mp4" loop="loop">

				<source src="<?php echo $sliderdata['video_mp4']; ?>" type="video/mp4; codecs=&quot;avc1.42E01E, mp4a.40.2&quot;">

				<source src="<?php echo $sliderdata['video_webm']; ?>" type="video/webm; codecs=&quot;vp8, vorbis&quot;">

				<source src="<?php echo $sliderdata['video_ogv']; ?>" type="video/ogg; codecs=&quot;theora, vorbis&quot;">

				</video> </a>

	</div>			        
</div>
<div class="col-left sidebar">
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner_right1')->toHtml(); ?>
</div>
<div class="clear"></div>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner_button')->toHtml(); ?>
<div class="clear"></div>
<div class="brand-slider">
<div class="container">
	<ul id="responsive">
	<?php 
		$parentCategoryId = 32;
		$cat = Mage::getModel('catalog/category')->load($parentCategoryId);
		$subcats = $cat->getChildren();			
		foreach(explode(',',$subcats) as $subCatid){
			$_category = Mage::getModel('catalog/category')->load($subCatid);
			if($_category->getIsActive() && $_category->getThumbnail()) {				
				echo '<li><a href="'.$_category->getURL().'" title="'.$_category->getName().'"><img src="'.$this->getUrl('media/catalog/category').$_category->getThumbnail().'" /></a></li>';
			}
		}		
		?>
	</ul>
</div>

</div>
<script type="text/javascript">
var video = document.getElementById('vidplayer');
video.addEventListener('click',function(){
  video.play();
},false);
</script>
<?php }?>
