<?php

$magicToolboxHelper = Mage::helper('magicslideshow/settings');
//if($magicToolboxHelper->isModuleOutputEnabled()) return;

//$moduleName = $this->getRequest()->getModuleName();         //catalog   review  checkout    catalog     cms     catalogsearch   catalogsearch   wishlist
//$this->getRequest()->getRouteName()                         //catalog   review  checkout    catalog     cms     catalogsearch   catalogsearch   wishlist
//$controllerName = $this->getRequest()->getControllerName(); //product   product cart        category    index   result          advanced        index
//$actionName = $this->getRequest()->getActionName();         //view      list    configure   view        index   index           result          configure

// $productPage = false;
// if(in_array($controllerName, array('product', 'cart'))) {
//     $page = 'product';
//     if($actionName == 'view') {
//         $productPage = true;
//     }
// } else if($controllerName == 'index' && ($actionName == 'configure' || $actionName == 'view')) {
//     $page = 'product';
//     if($actionName != 'view') {
//         //NOTE: if we need this for 'configure' action !?
//         $productPage = true;
//     }
// } else {
//     $page = 'category';
// }

$tool = $magicToolboxHelper->loadTool();
$tool->params->resetProfile();

$force = $tool->params->checkValue('include-headers-on-all-pages', 'Yes', 'default');
$recentlyViewedProductsBlockEffectEnabled = !$tool->params->checkValue('enable-effect', 'No', 'recentlyviewedproductsblock');


$page = $this->getPageType();

if($page == 'cms_page') {
    $parentBlockAlias = $this->getParentBlock()->getBlockAlias();
    $pageIdentifier = Mage::getSingleton('cms/page')->getIdentifier();
    //NOTE: check for home page
    if($parentBlockAlias == 'head'/*'content' in template*/ && $pageIdentifier == 'home') {
        $page = 'home';
        $this->setPageType('home');
    } else {
        $tool->params->setValue('enable-effect', 'No', 'customslideshowblock');
    }
}
$customBlockEffectEnabled = ($page == 'home') && !$tool->params->checkValue('enable-effect', 'No', 'customslideshowblock');

if($force ||
   $recentlyViewedProductsBlockEffectEnabled ||
   $customBlockEffectEnabled ||
   ($tool->params->profileExists($page) && !$tool->params->checkValue('enable-effect', 'No', $page))) {
    echo $tool->getHeadersTemplate(str_replace('/magicslideshow.js', '', $this->getSkinUrl('js/magicslideshow.js')), str_replace('/magicslideshow.css', '', $this->getSkinUrl('css/magicslideshow/magicslideshow.css')));
}

?>
