<?php

$magicToolboxHelper = Mage::helper('magicslideshow/settings');
$tool = $magicToolboxHelper->loadTool('product');

$magic360ClassName = Mage::registry('magic360ClassName');
if($magic360ClassName) {
    $templateFilename = Mage::getSingleton('core/design_package')->getTemplateFilename($magic360ClassName.'/media.phtml');
} else {
    $templateFilename = $magicToolboxHelper->getTemplateFilename('product.info.media');
}
if($tool->params->checkValue('enable-effect', 'No') && !Mage::helper('mobiledetect')->isMobileDevice()) {
    require($templateFilename);
    return;
}

$_product = $this->getProduct();
$id = $_product->getId();
$_product_title = $title = $this->htmlEscape($_product->getName());
$main_image_file = $_product->getImage();
$main = '';
$scriptHTML = '';


$mainProductImages = array();
$associatedProductImages = array();

if(!$this->_isGalleryDisabled) {


    $iCount = count($this->getGalleryImages()->getItems());
    if($iCount) {
        foreach($this->getGalleryImages() as $_image) {
            $_image_file = $_image->getFile();
            $_image_path  = $_image->getPath();
            if(!file_exists($_image_path)) continue;
            $originalSizeArray = getimagesize($_image_path);
            $img = $this->helper('catalog/image')->init($_product, 'image', $_image_file)->__toString();
            if($tool->params->checkValue('square-images', 'Yes')) {
                $big_image_size = ($originalSizeArray[0] > $originalSizeArray[1]) ? $originalSizeArray[0] : $originalSizeArray[1];
                $img = $this->helper('catalog/image')->watermark(null, null)->resize($big_image_size)->__toString();
            }
            list($w, $h) = $magicToolboxHelper->magicToolboxGetSizes('thumb', $originalSizeArray);
            $medium = $this->helper('catalog/image')->watermark(null, null)->resize($w, $h)->__toString();
            list($w, $h) = $magicToolboxHelper->magicToolboxGetSizes('selector', $originalSizeArray);
            $thumb = $this->helper('catalog/image')->init($_product, 'thumbnail', $_image_file)->resize($w, $h)->__toString();
            $alt = $this->htmlEscape($_image->getLabel());

            $fullscreen = $img;
            $img = $medium;
            $mainProductImages[] = compact('img', 'thumb', 'fullscreen', 'title', 'alt');
        }
    }
    else {
        $tool->params->setValue('enable-effect', 'No');
        require($templateFilename);
        return;
    }
    $main = $tool->getMainTemplate($mainProductImages, array("id" => "productMagicSlideshow"),$_product);

}

echo $main;

echo '<img id="image" scr="" alt="" class="invisible" />';

?>
